version: 2
jobs:
  build-and-test:
    macos:
      xcode: "15.4.0"
    resource_class: m2pro.medium
    steps:
      - checkout
      - run: xcodebuild -version
      - run:
          name: Build and run tests
          command: cd ios && fastlane scan
          environment:
            SCAN_DEVICE: "iphone 8"
            SCAN_SCHEMA: CircleCIDemoReactNative
      - store_test_results:
          path: test_output/report.xml
workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test

        
      
