version: 2
jobs:
  version-check:
    steps:
      - run:
        name: Version Check
        cmd: circleci platform macos image list
  build-and-test:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Build and run tests
          command: cd ios && fastlane scan
          environment:
            SCAN_DEVICE: iphone 8
            SCAN_SCHEMA: CircleCIDemoReactNative
      - store_test_results:
          path: test_output/report.xml
workflows:
  version: 2
  build-and-test-workflow:
    jobs:
      - build-and-test
      - version-check
        
      
